// This file was generated by GitHub Copilot, using Claude Haiku 4.5.
import Battle from './battle.js';
import { createInstance, inputHandler, battleList } from './LocalCommand.js';

class BattleTestSuite {
    constructor(battle) {
        this.battle = battle;
        this.testsRun = 0;
        this.testsPassed = 0;
        this.testsFailed = 0;
    }

    test(testName, actual, expected) {
        this.testsRun++;
        const passed = JSON.stringify(actual) === JSON.stringify(expected);
        
        if (passed) {
            this.testsPassed++;
            console.log(`✓ PASS: ${testName}`);
        } else {
            this.testsFailed++;
            console.log(`✗ FAIL: ${testName}`);
            this.battle.error(`Test failed: ${testName}`);
        }
        console.log(`  Expected: ${JSON.stringify(expected)}`);
        console.log(`  Actual:   ${JSON.stringify(actual)}`);
        console.log('');
    }

    testEqual(testName, actual, expected) {
        this.testsRun++;
        const passed = actual === expected;
        
        if (passed) {
            this.testsPassed++;
            console.log(`✓ PASS: ${testName}`);
        } else {
            this.testsFailed++;
            console.log(`✗ FAIL: ${testName}`);
            this.battle.error(`Test failed: ${testName}`);
        }
        console.log(`  Expected: ${expected}`);
        console.log(`  Actual:   ${actual}`);
        console.log('');
    }

    testType(testName, actual, expectedType) {
        this.testsRun++;
        const passed = typeof actual === expectedType;
        
        if (passed) {
            this.testsPassed++;
            console.log(`✓ PASS: ${testName}`);
        } else {
            this.testsFailed++;
            console.log(`✗ FAIL: ${testName}`);
            this.battle.error(`Test failed: ${testName}`);
        }
        console.log(`  Expected type: ${expectedType}`);
        console.log(`  Actual type:   ${typeof actual}`);
        console.log(`  Actual value:  ${actual}`);
        console.log('');
    }

    testTruthy(testName, actual) {
        this.testsRun++;
        const passed = !!actual;
        
        if (passed) {
            this.testsPassed++;
            console.log(`✓ PASS: ${testName}`);
        } else {
            this.testsFailed++;
            console.log(`✗ FAIL: ${testName}`);
            this.battle.error(`Test failed: ${testName}`);
        }
        console.log(`  Expected: truthy`);
        console.log(`  Actual:   ${actual}`);
        console.log('');
    }

    printSummary() {
        console.log('\n========================================');
        console.log('TEST SUMMARY');
        console.log('========================================');
        console.log(`Total Tests: ${this.testsRun}`);
        console.log(`Passed: ${this.testsPassed}`);
        console.log(`Failed: ${this.testsFailed}`);
        console.log(`Pass Rate: ${((this.testsPassed / this.testsRun) * 100).toFixed(2)}%`);
        console.log('========================================\n');
    }
}

// Run tests
// Create Battle instance
console.clear();
const battle = new Battle('gameId123');
const suite = new BattleTestSuite(battle);

// =============================================
// Test: Constructor and Initialization
// =============================================
console.log('--- Constructor and Initialization ---\n');

suite.testEqual('playerTurn initialized to 1', battle.playerTurn, 1);
//suite.testEqual('playerAction initialized to attack', battle.playerAction, 'attack');
suite.test('p1ShipData is empty object', battle.p1ShipData, {});
suite.test('p1AttackData is empty object', battle.p1AttackData, {});
suite.test('p2ShipData is empty object', battle.p2ShipData, {});
suite.test('p2AttackData is empty object', battle.p2AttackData, {});
suite.testEqual('gridRows is 10', battle.gridRows, 10);
suite.testEqual('gridCols is 10', battle.gridCols, 10);
suite.testType('player1Id is string', battle.player1Id, 'string');
suite.testType('player2Id is string', battle.player2Id, 'string');
suite.testEqual('gameId stored correctly', battle.gameId, 'gameId123');

// =============================================
// Test: generatePlayerId
// =============================================
console.log('\n--- generatePlayerId ---\n');

const playerId1 = battle.generatePlayerId();
const playerId2 = battle.generatePlayerId(8);
suite.testEqual('generatePlayerId default length is 16', playerId1.length, 16);
suite.testEqual('generatePlayerId custom length works', playerId2.length, 8);
suite.testType('generatePlayerId returns string', playerId1, 'string');
suite.testTruthy('generatePlayerId produces non-empty ID', playerId1);

// =============================================
// Test: getOtherPlayer
// =============================================
console.log('\n--- getOtherPlayer ---\n');

suite.testEqual('getOtherPlayer(1) returns 2', battle.getOtherPlayer(1), 2);
suite.testEqual('getOtherPlayer(2) returns 1', battle.getOtherPlayer(2), 1);
suite.testEqual('getOtherPlayer() default returns other of current', battle.getOtherPlayer(), 2);

// =============================================
// Test: Cord Converters (new ":" format)
// =============================================
console.log('\n--- Cord Converters ---\n');

const stringCord = "5:3";
const arrayCord = [5, 3];

const convertedToArray = battle.stringToArrayCordConverter(stringCord);
const convertedToString = battle.arrayToStringCordConverter(arrayCord);

suite.test('stringToArrayCordConverter converts "5:3" to [5,3]', convertedToArray, [5, 3]);
suite.testEqual('arrayToStringCordConverter converts [5,3] to "5:3"', convertedToString, "5:3");
suite.test('cordConverter with string input', battle.cordConverter("7:8"), [7, 8]);
suite.testEqual('cordConverter with array input', battle.cordConverter([7, 8]), "7:8");

// =============================================
// Test: Data Selectors
// =============================================
console.log('\n--- Data Selectors ---\n');

const p1ShipList = battle.selectShipList(1);
const p2ShipList = battle.selectShipList(2);
const p1ShipData = battle.selectShipData(1);
const p2ShipData = battle.selectShipData(2);
const p1AttackData = battle.selectAttackData(1);
const p2AttackData = battle.selectAttackData(2);

suite.testEqual('selectShipList(1) returns p1ShipList reference', p1ShipList, battle.p1ShipList);
suite.testEqual('selectShipList(2) returns p2ShipList reference', p2ShipList, battle.p2ShipList);
suite.testEqual('selectShipData(1) returns p1ShipData reference', p1ShipData, battle.p1ShipData);
suite.testEqual('selectShipData(2) returns p2ShipData reference', p2ShipData, battle.p2ShipData);
suite.testEqual('selectAttackData(1) returns p1AttackData reference', p1AttackData, battle.p1AttackData);
suite.testEqual('selectAttackData(2) returns p2AttackData reference', p2AttackData, battle.p2AttackData);

// =============================================
// Test: Ship Placement Validation (new API)
// =============================================
console.log('\n--- Ship Placement Validation ---\n');

// Build ship cell arrays using the new helper
const shipCellsRight = battle.shipCordsFromStartDirectionLength("0:0", "right", 3);
suite.testType('shipCordsFromStartDirectionLength returns an array', shipCellsRight, 'object');

// Validate the generated cells
const validationRight = battle.validateShipPlacement(shipCellsRight);
suite.test('validateShipPlacement (new) valid ship right', validationRight, []);

// Out-of-bounds case
const shipCellsOut = battle.shipCordsFromStartDirectionLength("9:0", "right", 3);
const validationOut = battle.validateShipPlacement(shipCellsOut);
suite.testTruthy('validateShipPlacement (new) out of bounds returns invalid cells', validationOut && validationOut.length > 0);

// =============================================
// Test: Ship Deployment and Management (new API)
// =============================================
console.log('\n--- Ship Deployment and Management ---\n');

// Use the generator to create ship cells and deploy
const newShipCells = battle.shipCordsFromStartDirectionLength("0:0", "right", 3);
const validateBeforeDeploy = battle.validateShipPlacement(newShipCells);
suite.test('validate before deploy returns no invalid cells', validateBeforeDeploy, []);

const deployResult = battle.deployShip(newShipCells);
suite.testTruthy('deployShip returned a result (array or truthy)', deployResult !== undefined);

// Check that cells were marked on current player's shipData
// Convert expected cell keys to the string format used by the game if needed
const expectedKey0 = Array.isArray(newShipCells[0]) ? `${newShipCells[0][0]}:${newShipCells[0][1]}` : newShipCells[0];
suite.testEqual('deployShip marks first cell as ship in shipData', battle.p1ShipData[expectedKey0], 'ship');

// Test identifyShipFromCell using string key (convert center cell)
const centerKey = Array.isArray(newShipCells[1]) ? `${newShipCells[1][0]}:${newShipCells[1][1]}` : newShipCells[1];
const identifiedShip = battle.identifyShipFromCell(centerKey);
suite.testTruthy('identifyShipFromCell returns ship data for deployed ship', identifiedShip);

// =============================================
// Test: Attack Logic
// =============================================
console.log('\n--- Attack Logic ---\n');

// Switch to player 2 and attack player 1's ship
battle.playerTurn = 2;
battle.attack("0:0");

suite.testEqual('attack marks hit on ship in shipData', battle.p1ShipData["0:0"], "hit");
suite.testEqual('attack records hit in attackData', battle.p2AttackData["0:0"], "hit");

// Attack on empty cell
battle.attack("5:5");
suite.testEqual('attack marks miss on empty cell', battle.p1ShipData["5:5"], "miss");
suite.testEqual('attack records miss in attackData', battle.p2AttackData["5:5"], "miss");

// =============================================
// Test: Turn Management
// =============================================
console.log('\n--- Turn Management ---\n');

battle.playerTurn = 1;
battle.endTurn();
suite.testEqual('endTurn switches to player 2', battle.playerTurn, 2);
battle.endTurn();
suite.testEqual('endTurn switches back to player 1', battle.playerTurn, 1);

// =============================================
// Test: Reset and Random Cells
// =============================================
console.log('\n--- Reset and Random Cells ---\n');

battle.testChangeRandomCells();
const hasRandomShips = Object.keys(battle.p1ShipData).length > 0;
suite.testTruthy('testChangeRandomCells fills random cells', hasRandomShips);

battle.testResetMaps();
suite.test('testResetMaps clears all data', battle.p1ShipData, {});
suite.test('testResetMaps clears p2ShipData', battle.p2ShipData, {});
suite.test('testResetMaps clears p1AttackData', battle.p1AttackData, {});
suite.test('testResetMaps clears p2AttackData', battle.p2AttackData, {});

// =============================================
// Test: Game Over Logic
// =============================================
console.log('\n--- Game Over Logic ---\n');

// Reset game state for clean testing
battle.testResetMaps();

// Test: Game ongoing (both players have ships)
battle.p1ShipData["0:0"] = "ship";
battle.p2ShipData["0:0"] = "ship";
const gameOngoing = battle.checkGameOver();
suite.testEqual('checkGameOver returns 0 when both players have ships', gameOngoing, 0);

// Test: Player 1 wins (all of player 2's ships are hit/sunk)
battle.testResetMaps();
battle.p1ShipData["0:0"] = "ship"; // Player 1 still has a ship
battle.p2ShipData["0:0"] = "hit";  // Player 2's ship is hit/sunk
const p1Wins = battle.checkGameOver();
suite.testEqual('checkGameOver returns 1 when player 1 wins', p1Wins, 1);

// Test: Player 2 wins (all of player 1's ships are hit/sunk)
battle.testResetMaps();
battle.p1ShipData["0:0"] = "hit";  // Player 1's ship is hit/sunk
battle.p2ShipData["0:0"] = "ship"; // Player 2 still has a ship
const p2Wins = battle.checkGameOver();
suite.testEqual('checkGameOver returns 2 when player 2 wins', p2Wins, 2);

// Test: Game ongoing with mixed ship states
battle.testResetMaps();
battle.p1ShipData["0:0"] = "ship";
battle.p1ShipData["0:1"] = "hit";  // Player 1 has one ship remaining
battle.p2ShipData["0:0"] = "hit";
battle.p2ShipData["0:1"] = "ship"; // Player 2 has one ship remaining
const gameOngoingMixed = battle.checkGameOver();
suite.testEqual('checkGameOver returns 0 with mixed ship states', gameOngoingMixed, 0);

// Test: Empty game state (no ships placed)
battle.testResetMaps();
const emptyGame = battle.checkGameOver();
//suite.testEqual('checkGameOver returns 0 with no ships placed', emptyGame, 0);

// =============================================
// Test: LocalCommand Integration
// =============================================
console.log('\n--- LocalCommand Integration ---\n');

// Test: createInstance creates and stores a new battle
createInstance();
const gameIds = Object.keys(battleList);
suite.testTruthy('createInstance creates a battle instance', gameIds.length > 0);

// Get the created game ID for further testing
const testGameId = gameIds[0];
suite.testEqual('created battle has correct structure', typeof battleList[testGameId], 'object');

// Test: Get player IDs from the created battle
const createdBattle = battleList[testGameId];
const player1Id = createdBattle.player1Id;
const player2Id = createdBattle.player2Id;
suite.testType('player1Id is a string', player1Id, 'string');
suite.testType('player2Id is a string', player2Id, 'string');
suite.testTruthy('player1Id and player2Id are different', player1Id !== player2Id);

// =============================================
// Test: inputHandler with Deploy Action
// =============================================
console.log('\n--- inputHandler Deploy Action ---\n');

// Prepare ship deployment data for player 1
const deploymentDetails = {
    gameId: testGameId,
    playerId: player1Id,
    actionDetails: [["0:0", "right", 3]], // shipCordsArray from shipCordsFromStartDirectionLength
    action: "deploy"
};

const deploymentInput = JSON.stringify(deploymentDetails);
const deploymentResult = JSON.parse(inputHandler(deploymentInput));

suite.testTruthy('inputHandler returns result object', deploymentResult !== undefined);
suite.testTruthy('deployment actionData contains deployed ship', deploymentResult.actionData && deploymentResult.actionData.length > 0);
suite.testEqual('deployment returns correct player turn', deploymentResult.playerTurn, 1);
//suite.testEqual('deployment returns correct action', deploymentResult.playerAction, 'attack');
suite.testTruthy('deployment returns fleet data', Object.keys(deploymentResult.fleet).length > 0);

// =============================================
// Test: inputHandler with Invalid Game ID
// =============================================
console.log('\n--- inputHandler Error Handling ---\n');

const invalidGameDetails = {
    gameId: 'INVALID',
    playerId: player1Id,
    actionDetails: ["5:5"]
};

const invalidInput = JSON.stringify(invalidGameDetails);
const invalidResult = JSON.parse(inputHandler(invalidInput));

suite.testTruthy('inputHandler returns error for invalid game ID', invalidResult.error !== undefined);
suite.testEqual('error message is descriptive', invalidResult.error, 'Invalid Game ID');

// =============================================
// Test: inputHandler with Attack Action
// =============================================
console.log('\n--- inputHandler Attack Action ---\n');

// Create a new battle for attack testing
createInstance();
const newGameIds = Object.keys(battleList);
const attackGameId = newGameIds[newGameIds.length - 1];
const attackBattle = battleList[attackGameId];

// Deploy ships for both players
const p1AttackPlayerId = attackBattle.player1Id;
const p2AttackPlayerId = attackBattle.player2Id;

// Deploy ship for player 1
const p1DeployDetails = {
    gameId: attackGameId,
    playerId: p1AttackPlayerId,
    actionDetails: [["0:0", "right", 3]],
    action: "deploy"
};
const p1DeployResult = JSON.parse(inputHandler(JSON.stringify(p1DeployDetails)));
suite.testEqual('player 1 deployment successful', typeof p1DeployResult.actionData, 'object');
attackBattle.endTurn(); // Switch to player 2 turn

// Deploy ship for player 2 (via endTurn logic in attack scenario)
const p2DeployDetails = {
    gameId: attackGameId,
    playerId: p2AttackPlayerId,
    actionDetails: [["5:5", "down", 3]],
    action: "deploy"
};
const p2DeployResult = JSON.parse(inputHandler(JSON.stringify(p2DeployDetails)));
suite.testEqual('player 2 deployment successful', typeof p2DeployResult.actionData, 'object');

attackBattle.endTurn(); // Switch back to player 1 turn

const p1AttackDetails = {
    gameId: attackGameId,
    playerId: p1AttackPlayerId,
    actionDetails: [["5:5"]],
    action: "attack"
};
const p1AttackResult = JSON.parse(inputHandler(JSON.stringify(p1AttackDetails)));
suite.testEqual('player 1 attack successful', typeof p1AttackResult.actionData, 'object');
console.log(p1AttackResult);
attackBattle.endTurn(); // Switch to player 2 turn

// Deploy ship for player 2 (via endTurn logic in attack scenario)
const p2AttackDetails = {
    gameId: attackGameId,
    playerId: p2AttackPlayerId,
    actionDetails: [["0:0"]],
    action: "deploy"
};
const p2AttackResult = JSON.parse(inputHandler(JSON.stringify(p2AttackDetails)));
suite.testEqual('player 2 attack successful', typeof p2AttackResult.actionData, 'object');
console.log(p2AttackResult);


// =============================================
// Test: inputHandler Data Isolation
// =============================================
console.log('\n--- inputHandler Data Isolation ---\n');

// Verify that different game instances have isolated data
suite.testTruthy('testGameId battle is isolated from attackGameId battle', testGameId !== attackGameId);
// suite.testTruthy('player1 fleet in first game differs from player1 fleet in second game', JSON.stringify(battleList[testGameId].p1ShipData) !== JSON.stringify(battleList[attackGameId].p1ShipData));

// =============================================
// Test: inputHandler with Correct Player Turn
// =============================================
console.log('\n--- inputHandler Player Turn Validation ---\n');

// Test attacking with correct player turn
const attackDetails = {
    gameId: attackGameId,
    playerId: p2AttackPlayerId,
    actionDetails: [["0:0"]]
};

const attackResult = JSON.parse(inputHandler(JSON.stringify(attackDetails)));
suite.testEqual('attack result contains hit status', attackResult.actionData[0], 'hit');
suite.testTruthy('attack records in attack data', Object.keys(attackResult.attacks).length > 0);

// =============================================
// Test: inputHandler Return Data Structure
// =============================================
console.log('\n--- inputHandler Return Data Structure ---\n');

// Verify complete return data structure
suite.testTruthy('return data has actionData field', deploymentResult.actionData !== undefined);
suite.testTruthy('return data has fleet field', deploymentResult.fleet !== undefined);
suite.testTruthy('return data has attacks field', deploymentResult.attacks !== undefined);
suite.testTruthy('return data has playerTurn field', deploymentResult.playerTurn !== undefined);
suite.testTruthy('return data has playerAction field', deploymentResult.playerAction !== undefined);

// =============================================
// Print Summary
// =============================================
suite.printSummary();